/**
 * 7th Rank SEO Audit Agent
 *
 * Reads the live site HTML and runs a comprehensive SEO audit via Claude.
 * Outputs a timestamped markdown report to agents/reports/
 *
 * Usage:
 *   node agents/seo-audit.js
 *   node agents/seo-audit.js --keyword "chess hoodie"   (adds keyword gap analysis)
 */

require('dotenv').config();
const Anthropic = require('@anthropic-ai/sdk');
const fs = require('fs');
const path = require('path');

const HTML_PATH = path.join(__dirname, '../website/index.html');
const REPORTS_DIR = path.join(__dirname, 'reports');
const SITE_URL = 'https://www.7th-rank.com';

const BRAND_CONTEXT = `
7th Rank is a luxury chess-inspired streetwear brand. Their debut collection is "First Move".
Product lines: Stoic, Grain, Thin Ice (TI), Pasture, Harmony.
Garment types: hoodies, tees (Pawn, Bishop, Knight, Rook, Queen, King graphics).
Target audience: chess enthusiasts, streetwear buyers, 18–35 demographic.
Price range: premium ($80–$160 estimated).
Domain: www.7th-rank.com
Primary competitors: chess.com merch, chess-related Etsy sellers, niche streetwear brands.
`.trim();

async function run() {
  if (!process.env.ANTHROPIC_API_KEY || process.env.ANTHROPIC_API_KEY === 'your_api_key_here') {
    console.error('Error: Set ANTHROPIC_API_KEY in your .env file.');
    process.exit(1);
  }

  const targetKeyword = process.argv.includes('--keyword')
    ? process.argv[process.argv.indexOf('--keyword') + 1]
    : null;

  console.log('Reading site HTML...');
  const html = fs.readFileSync(HTML_PATH, 'utf8');

  // Extract just the <head> and visible text content to stay within context limits
  const head = html.match(/<head[\s\S]*?<\/head>/i)?.[0] || '';
  const bodyText = html
    .replace(/<script[\s\S]*?<\/script>/gi, '')
    .replace(/<style[\s\S]*?<\/style>/gi, '')
    .replace(/<[^>]+>/g, ' ')
    .replace(/\s+/g, ' ')
    .trim()
    .slice(0, 6000); // cap body text

  const client = new Anthropic.default();

  console.log('Running SEO audit with Claude...\n');

  const message = await client.messages.create({
    model: 'claude-sonnet-4-6',
    max_tokens: 4096,
    system: `You are a senior SEO strategist specializing in e-commerce and niche fashion brands.
You write clear, actionable audit reports in markdown. Be specific — cite exact tag values,
character counts, and missing elements. Prioritize recommendations by impact (High/Medium/Low).
Brand context: ${BRAND_CONTEXT}`,
    messages: [
      {
        role: 'user',
        content: `Perform a comprehensive SEO audit for 7th Rank (${SITE_URL}).

## Site <head> HTML:
\`\`\`html
${head}
\`\`\`

## Visible body text (sample):
${bodyText}

## Audit checklist — evaluate each section:

1. **Title Tag** — length (ideal 50–60 chars), keyword placement, brand clarity
2. **Meta Description** — length (ideal 150–160 chars), CTA presence, keyword inclusion
3. **Heading Structure** — H1 presence/uniqueness, H2–H3 hierarchy, keyword coverage
4. **Open Graph & Twitter Cards** — completeness, image dimensions, missing fields
5. **Schema Markup** — type correctness, required fields, enhancement opportunities
6. **Keyword Strategy** — primary/secondary keyword targeting, gaps for chess + apparel searches
7. **Content Gaps** — what informational content is missing that would attract organic traffic
8. **Technical SEO** — canonical, robots meta, mobile/PWA signals, sitemap reference
9. **Quick Wins** — 3–5 changes that can be made in under an hour with high impact
${targetKeyword ? `10. **Keyword Gap: "${targetKeyword}"** — how well does the site target this term and what's needed to rank?` : ''}

Format the output as a clean markdown report with an executive summary at the top.
Include a priority action table at the end (columns: Action | Impact | Effort | Owner).`,
      },
    ],
  });

  const report = message.content[0].text;

  // Save report
  if (!fs.existsSync(REPORTS_DIR)) fs.mkdirSync(REPORTS_DIR, { recursive: true });
  const timestamp = new Date().toISOString().slice(0, 10);
  const reportPath = path.join(REPORTS_DIR, `seo-audit-${timestamp}.md`);
  const header = `# 7th Rank SEO Audit — ${timestamp}\nGenerated by: agents/seo-audit.js\n\n---\n\n`;
  fs.writeFileSync(reportPath, header + report);

  console.log(report);
  console.log(`\n---\nReport saved: ${reportPath}`);
}

run().catch(err => { console.error(err.message); process.exit(1); });
